/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter */

#ifndef _Included_edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter
#define _Included_edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter
 * Method:    runOpenCVWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter_runOpenCVWindow
  (JNIEnv *, jobject);

/*
 * Class:     edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter
 * Method:    stopOpenCVWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter_stopOpenCVWindow
  (JNIEnv *, jobject);

/*
 * Class:     edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter
 * Method:    getNumberOfDetectedFaces
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter_getNumberOfDetectedFaces
  (JNIEnv *, jobject);

/*
 * Class:     edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter
 * Method:    storeCurrentFace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_kit_anthropomatik_isl_DialogModeling_OpenCV_OpenCVAdapter_storeCurrentFace
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
