package edu.kit.anthropomatik.isl.DialogModeling.State;

public enum Trigger {
	INITIALIZED, NO_FACE_DETECTED, FACE_DETECTED, USER_RECOGNIZED, USER_NOT_RECOGNIZED,
	USER_UNKNOWN, NOT_UNDERSTOOD, USER_GREETS, WANT_HELP, USER_HELPING, USER_NOT_HELPING,
	JOB_DONE, DIALOG_DONE, SELF_TALK_OVER
}